# Generated by Django 3.2 on 2021-04-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210420_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='ststus',
            new_name='status',
        ),
    ]
